# Generated by Django 4.1 on 2022-08-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_alter_mailing_filter_field_and_more'),
        ('customer', '0002_alter_customer_operator_code_and_more'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Отправлено клиенту:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='mailing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing.mailing', verbose_name='Отправлено в рамках рассылки:'),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Статус'),
        ),
    ]
