version: '3.7'
services:
  backend:
    build: .
    command: >
      sh -c "python backend/manage.py makemigrations && python backend/manage.py migrate && python backend/manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'

  redis:
    image: redis:alpine
    restart: always
    expose:
      - '6379'
    ports:
      - '6379:6379'

  celery:
    build: .
    command: celery -A config worker -Q discounts,garbage_remove
    depends_on:
      - redis
      - backend