# Generated by Django 4.1 on 2022-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='tag',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
