# Generated by Django 4.1 on 2022-08-11 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_datetime', models.DateTimeField(auto_now_add=True, verbose_name='Время рассылки')),
                ('message_text', models.TextField()),
                ('end_datetime', models.DateTimeField()),
            ],
        ),
    ]
