# Generated by Django 4.1 on 2022-08-17 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailingFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator_code', models.IntegerField()),
                ('tag', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='mailing',
            name='filter_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingfilter'),
        ),
    ]
