# Generated by Django 4.1 on 2022-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время рассылки'),
        ),
    ]
