# Generated by Django 4.1 on 2022-09-02 13:18

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mailing',
            managers=[
                ('mailings', django.db.models.manager.Manager()),
            ],
        ),
    ]
