# Generated by Django 4.1 on 2022-09-02 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_mailing_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='mailing',
            managers=[
            ],
        ),
    ]
