# Generated by Django 4.1 on 2022-08-18 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0003_alter_mailing_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='filter_field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.mailingfilter', verbose_name='Фильтрация'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='message_text',
            field=models.TextField(verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='mailingfilter',
            name='operator_code',
            field=models.IntegerField(verbose_name='Код оператора'),
        ),
        migrations.AlterField(
            model_name='mailingfilter',
            name='tag',
            field=models.CharField(blank=True, max_length=50, verbose_name='Тег'),
        ),
    ]
